name: Python Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel build cython
        pip install -r requirements.txt || echo "No requirements.txt found"

    - name: Build Cython extensions (if any)
      run: python setup.py build_ext --inplace || echo "No Cython extensions found"

    - name: Run tests
      run: echo "No tests defined yet"

    - name: Build package
      run: python -m build

    - name: Upload to PyPI
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: pypa/gh-action-pypi-publish@v1.5.2
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
