name: Python Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cython setuptools wheel
        pip install -r requirements.txt || echo "No requirements.txt found"

    - name: Build Cython extensions
      run: python setup.py build_ext --inplace

    - name: Run tests
      run: |
        # Add your test commands here, e.g. pytest
        echo "No tests defined yet"

    - name: Package
      run: python setup.py sdist bdist_wheel

    - name: Upload to PyPI
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: pypa/gh-action-pypi-publish@v1.5.2
      with:
        password: \${{ secrets.PYPI_API_TOKEN }}
